scss_files: 'app/**/*.scss'
linters:
  BorderZero:
    enabled: false
  Indentation:
    severity: warning
    width: 2
  SelectorFormat:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  LeadingZero:
    enabled: false
  SelectorDepth:
    enabled: false
  NestingDepth:
    enabled: false
