template_path: sc-cloud-watch-alarm.yaml
stack_name: {{project_code}}-cloudwatch-alarm
parameters:
  ClusterName: {{cluster_name}}
  ServiceName: {{service_name}}
  DevelopmentTeam: {{development_team}}
  DevelopmentEnvironment: {{development_environment}}
  MinContainers: {{min_containers_count}}
