template_path: sc-fargate-service.yaml
stack_name: {{project_code}}-fargate-service
parameters:
  ClusterName: {{project_code}}-cluster
  ECRRepoSuffix: dkr.ecr.{{region}}.amazonaws.com/com.godaddy.{{project_code}}
  ServiceName: {{project_code}}-fargate
  CertificateId: {{certificate_id}}
  HealthCheckPath: /healthcheck
  HealthCheckGracePeriodSeconds: "240"
  TrafficType: internal
  ProductVersion: {{fargate_service_version}}
  CustomIAMRoleNameSuffix: custom-fargate-role
  DesiredContainers: "1"
  MinContainers: "1"
  MaxContainers: "3"
  ContainerPort: "8443"
  ContainerProtocol: "HTTPS"
  Cpu: "1024"
  Memory: "2GB"
  EnvironmentVariablesJson: "[{\"Name\":\"NODE_ENV\",\"Value\":\"{{node_env}}\"},{\"Name\":\"AWS\",\"Value\":\"true\"}]"
dependencies:
  - {{environment}}/{{region}}/{{project_code}}/fargate-cluster.yaml
