template_path: sc-sns-moog.yaml
stack_name: {{project_code}}-sns-moog
parameters:
  #ProvisionedProductName: "sns-alerting-dev-private"
  SnsMoogTopicNameSuffix: {{ region }}-Threat-Research-{{ environment }}
