AWSTemplateFormatVersion: 2010-09-09
Description: CloudWatch Alarm
Parameters:
  ClusterName:
    Type: String
  DevelopmentTeam:
    Type: String
  DevelopmentEnvironment:
    Type: String
Resources:
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}::warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}::warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}
      AlarmDescription: !Sub fires when any container in the ${ClusterName} cluster has CPU Utilization over the threshold of 50 percent
      AlarmName: !Sub CPU Utilization for ${DevelopmentEnvironment} ${ClusterName}
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: "ClusterName"
          Value: !Sub ${ClusterName}
        - Name: "ServiceName"
          Value: !Sub ${ServiceName}
      EvaluationPeriods: 10
      MetricName: CPUUtilization
      Namespace: 'AWS/ECS'
      Period: 60
      Statistic: Average
      Threshold: 50
      Unit: Percent
Outputs:
  AlarmName:
    Description: The name of the alarm.
    Value: !Ref Alarm
  AlarmArn:
    Description: The arn of the alarm.
    Value: !GetAtt Alarm.Arn
