AWSTemplateFormatVersion: 2010-09-09
Description: CloudWatch Alarm
Parameters:
  ClusterName:
    Type: String
  ServiceName:
    Type: String
  DevelopmentTeam:
    Type: String
  DevelopmentEnvironment:
    Type: String
  MinContainers:
    Type: String
Resources:
  CPUWarning:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when any container in the ${ClusterName} cluster has CPU Utilization over the threshold
      AlarmName: !Sub CPU Utilization for ${DevelopmentEnvironment} ${ClusterName}
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: "ClusterName"
          Value: !Sub ${ClusterName}
        - Name: "ServiceName"
          Value: !Sub ${ServiceName}
      EvaluationPeriods: 3
      MetricName: CPUUtilization
      Namespace: 'AWS/ECS'
      Period: 60
      Statistic: Average
      Threshold: 90
      Unit: Percent
