AWSTemplateFormatVersion: 2010-09-09
Description: CloudWatch Alarm
Parameters:
  ClusterName:
    Type: String
  ServiceName:
    Type: String
  DevelopmentTeam:
    Type: String
  DevelopmentEnvironment:
    Type: String
  LoadBalancerName:
    Type: String
  ProjectCode:
    Type: String
    Default: "THREAT-UI-TENET"
Resources:
  CPUWarning:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when any container in the ${ClusterName} cluster has CPU Utilization over the threshold
      AlarmName: !Sub "${ProjectCode}: CPU Utilization for ${DevelopmentEnvironment} ${ClusterName}"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: "ClusterName"
          Value: !Sub ${ClusterName}
        - Name: "ServiceName"
          Value: !Sub ${ServiceName}
      EvaluationPeriods: 10
      MetricName: CPUUtilization
      Namespace: 'AWS/ECS'
      Period: 60
      Statistic: Average
      Threshold: 90
      Unit: Percent
  MemoryWarning:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:slack-threattools-devthreat-ui-tenet-cluster
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:slack-threattools-devthreat-ui-tenet-cluster
      AlarmDescription: !Sub fires when any container in the ${ClusterName} cluster has Memory Utilization over the threshold
      AlarmName: !Sub "${ProjectCode}: Memory Utilization for ${DevelopmentEnvironment} ${ClusterName}"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: "ClusterName"
          Value: !Sub ${ClusterName}
        - Name: "ServiceName"
          Value: !Sub ${ServiceName}
      EvaluationPeriods: 3
      MetricName: MemoryUtilization
      Namespace: 'AWS/ECS'
      Period: 60
      Statistic: Average
      Threshold: 3
      Unit: Percent
  ContainersError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when less than 1 containers are running in the ${ClusterName} cluster
      AlarmName: !Sub "${ProjectCode}: Containers Count for ${DevelopmentEnvironment} ${ClusterName}"
      ComparisonOperator: LessThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "ClusterName"
          Value: !Sub ${ClusterName}
        - Name: "ServiceName"
          Value: !Sub ${ServiceName}
      EvaluationPeriods: 1
      MetricName: ContainerInstanceCount
      Namespace: 'ECS/ContainerInsights'
      Period: 60
      Statistic: Minimum
      Threshold: 1
  TasksError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when less than 1 Task for deployment is running in ${ClusterName} cluster
      AlarmName: !Sub "${ProjectCode}: Running Tasks for ${DevelopmentEnvironment} ${ClusterName}"
      ComparisonOperator: LessThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "ClusterName"
          Value: !Sub ${ClusterName}
        - Name: "ServiceName"
          Value: !Sub ${ServiceName}
      EvaluationPeriods: 1
      MetricName: RunningTaskCount
      Namespace: 'ECS/ContainerInsights'
      Period: 60
      Statistic: Minimum
      Threshold: 1
  ServiceError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when no Service is running in ${ClusterName} cluster
      AlarmName: !Sub "${ProjectCode}: Service for ${DevelopmentEnvironment} ${ClusterName}"
      ComparisonOperator: LessThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "ClusterName"
          Value: !Sub ${ClusterName}
        - Name: "ServiceName"
          Value: !Sub ${ServiceName}
      EvaluationPeriods: 1
      MetricName: ServiceCount
      Namespace: 'ECS/ContainerInsights'
      Period: 60
      Statistic: Minimum
      Threshold: 1
  ALB400CountError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when too many 4xx errors in ${LoadBalancerName} load balancer
      AlarmName: !Sub "${ProjectCode}: 4xx Errors for ${DevelopmentEnvironment} ${LoadBalancerName} load balancer"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "LoadBalancer"
          Value: !Sub ${LoadBalancerName}
      EvaluationPeriods: 1
      MetricName: HTTPCode_ELB_4XX_Count
      Namespace: 'AWS/ApplicationELB'
      Period: 60
      Statistic: Sum
      Threshold: 10
  ALB500CountError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when too many 5xx errors in ${LoadBalancerName} load balancer
      AlarmName: !Sub "${ProjectCode}: 5xx Errors for ${DevelopmentEnvironment} ${LoadBalancerName} load balancer"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "LoadBalancer"
          Value: !Sub ${LoadBalancerName}
      EvaluationPeriods: 1
      MetricName: HTTPCode_ELB_5XX_Count
      Namespace: 'AWS/ApplicationELB'
      Period: 60
      Statistic: Sum
      Threshold: 10
  ALBRejectedConnectionError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when too many rejected connection in ${LoadBalancerName} load balancer
      AlarmName: !Sub "${ProjectCode}: Rejected Connection for ${DevelopmentEnvironment} ${LoadBalancerName} load balancer"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "LoadBalancer"
          Value: !Sub ${LoadBalancerName}
      EvaluationPeriods: 1
      MetricName: RejectedConnectionCount
      Namespace: 'AWS/ApplicationELB'
      Period: 60
      Statistic: Sum
      Threshold: 10
  ALBHealthyTargetsError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when no healthy targets instances registered in ${LoadBalancerName} load balancer
      AlarmName: !Sub "${ProjectCode}: Healthy targets instances registered in ${DevelopmentEnvironment} ${LoadBalancerName} load balancer"
      ComparisonOperator: LessThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "LoadBalancer"
          Value: !Sub ${LoadBalancerName}
        - Name: "TargetGroup"
          Value: !Sub ${LoadBalancerName}
      EvaluationPeriods: 1
      MetricName: HealthyHostCount
      Namespace: 'AWS/ApplicationELB'
      Period: 60
      Statistic: Sum
      Threshold: 1
  ALBTargets400CountWarning:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:warning-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when too many 4xx errors coming from targets in ${LoadBalancerName} load balancer
      AlarmName: !Sub "${ProjectCode}: 4xx Errors in targets for ${DevelopmentEnvironment} ${LoadBalancerName} load balancer"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "LoadBalancer"
          Value: !Sub ${LoadBalancerName}
        - Name: "TargetGroup"
          Value: !Sub ${LoadBalancerName}
      EvaluationPeriods: 1
      MetricName: HTTPCode_Target_4XX_Count
      Namespace: 'AWS/ApplicationELB'
      Period: 60
      Statistic: Sum
      Threshold: 10
  ALBTargets500CountError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      OKActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:critical-moog-${DevelopmentTeam}-${DevelopmentEnvironment}${ClusterName}
      AlarmDescription: !Sub fires when too many 5xx errors coming from targets in ${LoadBalancerName} load balancer
      AlarmName: !Sub "${ProjectCode}: 5xx Errors in targets for ${DevelopmentEnvironment} ${LoadBalancerName} load balancer"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: "LoadBalancer"
          Value: !Sub ${LoadBalancerName}
        - Name: "TargetGroup"
          Value: !Sub ${LoadBalancerName}
      EvaluationPeriods: 1
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: 'AWS/ApplicationELB'
      Period: 60
      Statistic: Sum
      Threshold: 10
