Parameters:
  ClusterName:
    Type: String
    Description: (required) The name of the Fargate Cluster to deploy this Service to
  ECRRepoSuffix:
    Description: (required) The address to the ECR Repo where the ImageTag exists (everything after accountId.)
    Type: String
  ServiceName:
    Type: String
    Description: The name of the Fargate Service
  CertificateId:
    Type: String
    Description: (required) The CertificateId for the certificate in AWS Certificate Manager to use for Load Balancer HTTPS
  VPC:
    Type: String
    Description: (optional) SSM Parameter for VPC ID for cluster to live in
    Default: /AdminParams/VPC/ID
    AllowedPattern: '/AdminParams/VPC[2-9]{0,1}/ID'
  ImageTag:
    Type: String
    Description: (optional) The tag of the docker image to deploy in the Task definition
    Default: latest
  ProductVersion:
    Type: String
    Default: '1.3.0'
  EnvironmentVariablesJson:
    Type: String
    Default: '{}'
    Description: (optional) Pass environment variables to the Lambda function. This has to be a JSON escaped string.
  CustomIAMRoleNameSuffix:
    Type: String
    Description: (optional) Naming suffix for custom role (ex. team-custom-SUFFIX) for the containers to run as. Ensure the ECS service can assume it.
    Default: ''
  ContainerPort:
    Type: String
    Description: (optional) What port does the container expose
    Default: '8443'
  ContainerProtocol:
    Type: String
    Description: (optional) Protocol for ALB <-> Container connections
    Default: HTTP
    AllowedValues:
      - HTTP
      - HTTPS
  TrafficType:
    Type: String
    Description: (optional) Type of traffic that needs to be handled, defaulted to internal
    Default: internal
    AllowedValues:
      - internal
      - internet-facing
  HealthCheckPath:
    Type: String
    Description: (optional) The path to the healthcheck that Fargate uses to decide if the container is running or not
    Default: /healthcheck
  HealthCheckGracePeriodSeconds:
    Type: Number
    Description: (optional) This may need to be adjusted if the container takes a while to start up
    Default: 30
  MinContainers:
    Type: String
    Description: (optional) Min number of containers in the Autoscaling Group (0 to 20)
    Default: '0'
  DesiredContainers:
    Type: String
    Description: (optional) Desired/default number of containers in the Autoscaling Group (0 to 20)
    Default: '0'
  MaxContainers:
    Type: String
    Description: (optional) Max number of containers in the Autoscaling Group (1 to 20)
    Default: '5'
  Cpu:
    Type: String
    Description: (optional) How much Cpu to allocate for the container workloads
    Default: '256'
    AllowedValues:
      - '256' # (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
      - '512' # (.5 vCPU)  - Available memory values: 1GB, 2GB, 3GB, 4GB
      - '1024' # (1 vCPU)   - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
      - '2048' # (2 vCPU)   - Available memory values: Between 4GB and 16GB in 1GB increments
      - '4096' # (4 vCPU)   - Available memory values: Between 8GB and 30GB in 1GB increments
  Memory:
    Type: String
    Description: (optional) How much memory (in GB) to allocate to the container workloads
    Default: '0.5GB'
    AllowedValues:
      - '0.5GB' # Available cpu values: 256 (.25 vCPU)
      - '1GB' # Available cpu values: 256 (.25 vCPU), 512 (.5 vCPU)
      - '2GB' # Available cpu values: 256 (.25 vCPU), 512 (.5 vCPU), 1024 (1 vCPU)
      - '3GB' # Available cpu values: 512 (.5 vCPU), 1024 (1 vCPU)
      - '4GB' # Available cpu values: 512 (.5 vCPU), 1024 (1 vCPU), 2048 (2 vCPU)
      - '5GB' # Available cpu values: 1024 (1 vCPU), 2048 (2 vCPU)
      - '6GB' # Available cpu values: 1024 (1 vCPU), 2048 (2 vCPU)
      - '7GB' # Available cpu values: 1024 (1 vCPU), 2048 (2 vCPU)
      - '8GB' # Available cpu values: 1024 (1 vCPU), 2048 (2 vCPU)
      - '9GB' # Available cpu values: 2048 (2 vCPU), 4096 (4 vCPU)
      - '10GB' # Available cpu values: 2048 (2 vCPU), 4096 (4 vCPU)
      - '11GB' # Available cpu values: 2048 (2 vCPU), 4096 (4 vCPU)
      - '12GB' # Available cpu values: 2048 (2 vCPU), 4096 (4 vCPU)
      - '13GB' # Available cpu values: 2048 (2 vCPU), 4096 (4 vCPU)
      - '14GB' # Available cpu values: 2048 (2 vCPU), 4096 (4 vCPU)
      - '15GB' # Available cpu values: 2048 (2 vCPU), 4096 (4 vCPU)
      - '16GB' # Available cpu values: 2048 (2 vCPU), 4096 (4 vCPU)
  AccessLogsEnabled:
    Type: String
    Description: (optional) Enabled ALB access logging
    Default: true
Resources:
  FargateService:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: FargateService
      ProvisioningArtifactName: !Ref ProductVersion
      ProvisionedProductName: !Sub ${ServiceName}
      ProvisioningParameters:
        - Key: ClusterName
          Value: !Ref ClusterName
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: CertificateId
          Value: !Ref CertificateId
        - Key: ECRRepo
          Value: !Sub ${AWS::AccountId}.${ECRRepoSuffix}
        - Key: ImageTag
          Value: !Ref ImageTag
        - Key: PrivateTaskVPCSubnetParamName
          Value: /AdminParams/VPC/DXAPPSubnets
        - Key: LoadBalancerVPCSubnetParamName
          Value: /AdminParams/VPC/DXAPPSubnets
        - Key: TrafficType
          Value: !Ref TrafficType
        - Key: EnvironmentVariablesJson
          Value: !Ref EnvironmentVariablesJson
        - Key: CustomIAMRoleNameSuffix
          Value: !Ref CustomIAMRoleNameSuffix
        - Key: HealthCheckPath
          Value: !Ref HealthCheckPath
        - Key: HealthCheckGracePeriodSeconds
          Value: !Ref HealthCheckGracePeriodSeconds
        - Key: ContainerPort
          Value: !Ref ContainerPort
        - Key: ContainerProtocol
          Value: !Ref ContainerProtocol
        - Key: MinContainers
          Value: !Ref MinContainers
        - Key: DesiredContainers
          Value: !Ref DesiredContainers
        - Key: MaxContainers
          Value: !Ref MaxContainers
        - Key: Cpu
          Value: !Ref Cpu
        - Key: Memory
          Value: !Ref Memory
        - Key: AccessLogsEnabled
          Value: !Ref AccessLogsEnabled
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: true
