Parameters:
  ClusterName:
    Type: String
    Description: Required. The name of the Fargate Cluster
  ProductVersion:
    Type: String
    Default: '1.1.0'
  ContainerInsights:
    Type: String
    Description: (Optional) Whether Container Insights will be enabled for the cluster.
    Default: disabled
    AllowedValues:
      - enabled
      - disabled
Resources:
  FargateCluster:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: FargateCluster
      ProvisioningArtifactName: !Ref ProductVersion
      ProvisionedProductName: !Sub ${ClusterName}-cluster
      ProvisioningParameters:
        - Key: ClusterName
          Value: !Ref ClusterName
      Tags:
        - Key: doNotShutDown
          Value: true
