AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the SNS Service Catalog Product
Parameters:
  SnsTopicName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SNS Topic Name. This value will be pushed from the configs.yaml pertaining to the region or the account based on the team's requirement
    Default: /AdminParams/SNS/AlarmNotificationTopic
  TeamSlackWebHook:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for team slack webhook. Default value is in /AdminParams/SNS/AlarmNotificationTopic topic already
    Default: /AdminParams/Team/TeamSlackWebHook

Resources:
  SimpleNotificationService:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: SNS
      ProvisioningArtifactName: 1.0.13
      ProvisionedProductName: sns-integration-test
      ProvisioningParameters:
        - Key: SnsTopicName
          Value: !Ref SnsTopicName
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"
