AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the SNS Service Catalog Product
Parameters:
  SnsTopicName:
    Type: String
    Description: SNS Topic Name. This value will be pushed from the configs.yaml pertaining to the region or the account based on the team's requirement
  TeamSlackWebHook:
    Type: String
    Description: Slack webhook for notifications
    Default: ""
  PolicyDocument:
    Type: String
    Description: (optional) A policy document that contains permissions to add to the specified SNS topics.
    Default: ""
  QueueName:
    Type: String
    Description: SQS Queue name for notifications
    Default: ""
  KeyAlias:
    Type: String
    Description: The name of the key to be used for encryption.
  ConsumerListAccounts:
    Type: String
    Description: Comma delimited list of consumer account IDs that want access to this key.For updates, pass in all the consumer accounts along with the older ones.
    Default: ""

Resources:
  CrossAccountKMSKey:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: CrossAccountKMSKey
      ProvisioningArtifactName: latest
      ProvisionedProductName: generate-kms-key
      ProvisioningParameters:
        - Key: ConsumerListAccounts
          Value: !Sub ${AWS::AccountId}
        - Key: KeyAlias
          Value: !Ref KeyAlias
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"

  SimpleNotificationService:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: SNS
      ProvisioningArtifactName: latest
      ProvisionedProductName: sns-integration-test
      ProvisioningParameters:
        - Key: PolicyDocument
          Value: !Ref PolicyDocument
        - Key: SnsTopicName
          Value: !Ref SnsTopicName
        - Key: TeamSlackWebHook
          Value: !Ref TeamSlackWebHook
        - Key: QueueName
          Value: !Ref QueueName
        - Key: NeedEncryption
          Value: "true"
        - Key: KmsKeyId
          Value: !Sub "/Team/KmsShared/${KeyAlias}/KeyAliasArn"
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"
    DependsOn: CrossAccountKMSKey
