AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the IAM Custom Policy Service Catalog Product
Parameters:
  ProductVersion:
    Type: String
    Description: SC product version
    Default: 1.0.0
  PolicyNameSuffix:
    Type: String
    Description: Name of custom Policy appended to TeamName-custom-
  ServiceName:
    Type: String
Resources:
  IAMPolicy:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMPolicy
      ProvisioningArtifactName: !Ref ProductVersion
      ProvisionedProductName: !Sub ${ServiceName}-log-policy
      ProvisioningParameters:
        - Key: PolicyNameSuffix
          Value: !Ref PolicyNameSuffix
        - Key: PolicyJSON
          Value: !Sub |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Action": [
                    "kinesis:PutRecord",
                    "kinesis:PutRecords",
                    "firehose:PutRecord",
                    "firehose:PutRecordBatch"  
                  ],
                  "Effect": "Allow",
                  "Resource": [
                    "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/*",
                    "arn:aws:firehose:${AWS::Region}:${AWS::AccountId}:deliverystream/*"
                  ]
                }
              ]
            }
      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"