name: Deploy Role secrets automatic sync

# Access key rotation docs at https://github.secureserver.net/appservices/service-catalog-products/blob/master/IAMUser/README.md#access-key-rotation
on:
  #    Runs at 00:00 on Sunday UTC
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  sync-cloudservice-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Check out build actions
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          repository: gdcorp-actions/update-cloud-service-credentials
          token: ${{ secrets.REPO_CLONE_TOKEN_SA_PAT }}
          path: update-cloud-service-credentials

      - name: Configure dev-private credentials
        uses: aws-actions/configure-aws-credentials@bab55d3830fe69833c9fecaa51fe2c829a7508f3
        with:
          aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_ACCESS_KEY_ID_TEST }}
          aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_KEY_TEST }}
          role-to-assume: arn:aws:iam::345790377847:role/GD-AWS-USA-GD-ThreatTools-Dev-Private-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2
      - name: Update dev-private secrets
        uses: ./update-cloud-service-credentials
        env:
          GITHUB_TOKEN: ${{ secrets.AWS_SECRETS_SYNC_GH_PAT }}
        with:
          aws-secret-id: /Secrets/IAMUser/GD-AWS-DeployUser-ThreatTools-Dev-Private
          access-key-id-secret-name: DEV_PRIVATE_AWS_ACCESS_KEY_ID_TEST
          secret-access-key-secret-name: DEV_PRIVATE_AWS_SECRET_KEY_TEST
          org: gdcorp-infosec
          repository: threat-ui-tenet

      - name: Configure dev credentials
        uses: aws-actions/configure-aws-credentials@bab55d3830fe69833c9fecaa51fe2c829a7508f3
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_TOKEN_VALUE }}
          role-to-assume: arn:aws:iam::786677461057:role/GD-AWS-USA-GD-ThreatTools-Dev-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2
      - name: Update dev secrets
        uses: ./update-cloud-service-credentials
        env:
          GITHUB_TOKEN: ${{ secrets.AWS_SECRETS_SYNC_GH_PAT }}
        with:
          aws-secret-id: /Secrets/IAMUser/GD-AWS-DeployUser-ThreatTools-Dev
          access-key-id-secret-name: DEV_AWS_SECRET_ACCESS_KEY_ID
          secret-access-key-secret-name: DEV_AWS_SECRET_TOKEN_VALUE
          org: gdcorp-infosec
          repository: threat-ui-tenet

      - name: Configure prod credentials
        uses: aws-actions/configure-aws-credentials@bab55d3830fe69833c9fecaa51fe2c829a7508f3
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::338932590174:role/GD-AWS-USA-GD-ThreatTools-Prod-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2
      - name: Update prod secrets
        uses: ./update-cloud-service-credentials
        env:
          GITHUB_TOKEN: ${{ secrets.AWS_SECRETS_SYNC_GH_PAT }}
        with:
          aws-secret-id: /Secrets/IAMUser/GD-AWS-DeployUser-ThreatTools-Prod
          access-key-id-secret-name: PROD_AWS_ACCESS_KEY_ID
          secret-access-key-secret-name: PROD_AWS_SECRET_ACCESS_KEY
          org: gdcorp-infosec
          repository: threat-ui-tenet
