name: Deploy New Build

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/gasket.yml"

jobs:
  deploy:
    env:
      ECR_REPOSITORY: com.godaddy.threat-ui-tenet
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@05f0551dbd620d7be8d92f9f7c1674ebf6bcb0eb
        with:
          node-version: 12

      - name: Post status
        uses: actions/github-script@v3
        with:
          github-token: ${{github.token}}
          script: |
            github.request('POST /repos/' + context.repo.owner + '/' + context.repo.repo + '/statuses/' + context.sha, {
              sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'success',
              context:  'My New Context',
              description:   'My New Desc',
              target_url: 'https://www.godaddy.com'
            })

      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository.

      - name: Install node modules for root folder
        run: |
          npm i

      - name: Configure AWS credentials using Cloud Key Based Service Accounts
        uses: aws-actions/configure-aws-credentials@1ed6eed14f0f832cad5830fb357d937c2f20ec67
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_TOKEN_VALUE }}
          role-to-assume: ${{ secrets.DEV_AWS_DEPLOY_ROLE }}
          role-duration-seconds: 3600
          aws-region: us-west-2

      - name: Copy artificatory token into .npmrc
        working-directory: app
        run: |
          echo ${{ secrets.NPM_ARTIFACTORY_TOKEN }} >> .npmrc

#      - name: Install node modules
#        working-directory: app
#        run: |
#          npm i
#          export $(grep -v '^#' ../.varenv | xargs) && npm prune

#      - name: Build application code (also generate self-signed SSL certs)
#        working-directory: app
#        run: |
#          export $(grep -v '^#' ../.varenv | xargs) && npm run createcert
#          npm run build

      - name: Log into golden image ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 764525110978.dkr.ecr.us-west-2.amazonaws.com

      - name: Build docker container
        id: container
        run: |
          export $(grep -v '^#' .varenv | xargs) && docker build --build-arg NODE_ENV=$NODE_ENV -t tmp . | while read line ; do echo "$(date)| $line"; done;
          echo "::set-output name=id::$(docker images -q tmp)"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@a3b1dc9bc1598017eaab0d7f39725589b0bfb68b

      - name: Tag image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag ${{ steps.container.outputs.id }} $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Deploy image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Checkout GitHub Action for Scan Image
        uses: actions/checkout@v2
        with:
          repository: gdcorp-actions/container-scan
          ref: main
          token: ${{ secrets.SCANNER_ACTION_PAT_TOKEN }}
          path: .github/actions/container-scan

      - name: Scan Image For Vulnerabilities
        env:
          container-name: ${{ env.ECR_REPOSITORY}}:latest
          aws-account-id: 786677461057
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_TOKEN_VALUE }}
          role-to-assume: ${{ secrets.DEV_AWS_DEPLOY_ROLE }}
        uses: ./.github/actions/container-scan
        with:
          aws-access-key-id: ${{ env.aws-access-key-id }}
          aws-secret-access-key: ${{ env.aws-secret-access-key }}
          aws-region: ${{ env.aws-region }}
          aws-account-id: ${{ env.aws-account-id }}
          container-name: ${{ env.container-name }}
          role-to-assume: ${{ env.role-to-assume }}
          SCANNER_GOLDEN_AWS_SECRET_ACCESS_KEY_ID: ${{secrets.SCANNER_GOLDEN_AWS_SECRET_ACCESS_KEY_ID}}
          SCANNER_GOLDEN_AWS_SECRET_TOKEN_VALUE: ${{secrets.SCANNER_GOLDEN_AWS_SECRET_TOKEN_VALUE}}

      - name: Update ECS Fargate Cluster with new image
        run: |
          aws ecs update-service --cluster threat-ui-tenet-cluster --service threat-ui-tenet-fargate --force-new-deployment --region us-west-2
