name: Deploy New Build

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "Dockerfile"
      - ".varenv"
      - ".github/workflows/gasket.yml"

jobs:
  deploy:
    env:
      ECR_REPOSITORY: com.godaddy.threat-ui-tenet
    runs-on: self-hosted
    steps:
      - name: Set env variables for deployment
        id: set_vars
        run: |
          export $(grep -v '^#' .varenv | xargs)
          echo ::set-output name=NODE_ENV::${NODE_ENV}
          echo ::set-output name=GD_ROOT_DOMAIN::${GD_ROOT_DOMAIN}

      - name: Set params for development env
        if: steps.set_vars.outputs.NODE_ENV == 'development'
        run: |
          echo "AWS_DEPLOY_SECRET_ACCESS_KEY_ID=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_DEPLOY_SECRET_TOKEN_VALUE=${{ secrets.DEV_AWS_SECRET_TOKEN_VALUE }}" >> $GITHUB_ENV
          echo "AWS_DEPLOY_ROLE=${{ secrets.DEV_AWS_DEPLOY_ROLE }}" >> $GITHUB_ENV
          echo "AWS_CLUSTER_SSL_CERT_ID=6b8fa223-fcb8-4b58-b06e-49ee814098d0" >> $GITHUB_ENV
          echo "NODE_ENV=development" >> $GITHUB_ENV

      - name: Set params for production env
        if: steps.set_vars.outputs.NODE_ENV == 'production'
        run: |
          echo "AWS_DEPLOY_SECRET_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_DEPLOY_SECRET_TOKEN_VALUE=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEPLOY_ROLE=${{ secrets.PROD_AWS_DEPLOY_ROLE }}" >> $GITHUB_ENV
          echo "AWS_CLUSTER_SSL_CERT_ID=0ed4b93f-b7ad-4dba-9102-572cf48cc9ad" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - uses: actions/setup-node@4d0182af5ead0b7bf53e87e49aa959476f5501d3
        with:
          node-version: 12

      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository.

      - name: Install node modules for root folder
        run: |
          npm i

      - name: Configure AWS credentials using Cloud Key Based Service Accounts
        uses: aws-actions/configure-aws-credentials@0d9a5be0dceea74e09396820e1e522ba4a110d2f
        with:
          aws-access-key-id: ${{ env.AWS_DEPLOY_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_DEPLOY_SECRET_TOKEN_VALUE }}
          role-to-assume: ${{ env.AWS_DEPLOY_ROLE }}
          role-duration-seconds: 3600
          aws-region: us-west-2

      - name: Copy artificatory token into .npmrc
        working-directory: app
        run: |
          echo ${{ secrets.NPM_ARTIFACTORY_TOKEN }} >> .npmrc

      - name: Log into golden image ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 764525110978.dkr.ecr.us-west-2.amazonaws.com

      - name: Build docker container
        id: container
        run: |
          echo $NODE_ENV
          export $(grep -v '^#' .varenv | xargs) && docker build --build-arg NODE_ENV=$NODE_ENV -t tmp . | while read line ; do echo "$(date)| $line"; done;
          echo "::set-output name=id::$(docker images -q tmp)"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Tag image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag ${{ steps.container.outputs.id }} $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Configure AWS credentials using Cloud Key Based Service Accounts
        uses: aws-actions/configure-aws-credentials@0d9a5be0dceea74e09396820e1e522ba4a110d2f
        with:
          aws-access-key-id: ${{ env.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PROD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ env.PROD_AWS_DEPLOY_ROLE }}
          role-duration-seconds: 3600
          aws-region: us-west-2

#      - name: Checkout GitHub Action for Scan Image
#        uses: actions/checkout@v2
#        with:
#          repository: gdcorp-actions/container-scan
#          ref: main
#          token: ${{ secrets.SCANNER_ACTION_PAT_TOKEN }}  # ask for this PAT, it is needed to checkout code for scanning
#          path: .github/actions/container-scan


#      - name: Scan Images For Vulnerabilities
#        continue-on-error: true
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        uses: ./.github/actions/container-scan
#        with:
#          container-name: ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY}}
#          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
#          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
#          aws-session-token: ${{env.AWS_SESSION_TOKEN}}

      - name: Deploy image to ECR and Update ECS Fargate Cluster with new image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY
          aws ecs update-service --cluster threat-ui-tenet-cluster --service threat-ui-tenet-fargate --force-new-deployment --region us-west-2
